title:            The Fiery Lantern
description:      The Fiery Lantern - Phan Minh Dang's portfolio site.
url:              # Site url.
signoff:          Phan Minh Dang.
disqus_shortname: dg2701
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Email
    url:          mailto:thefierylantern@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/thefierylantern
    external:     true
pygments:         true
highlighter:      true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart